[project]
requires-python = "~=3.8"
dependencies = [
    "amaranth[builtin-yosys] @ git+https://github.com/amaranth-lang/amaranth.git",
]

[tool.pdm.scripts]
simulate = {call = "my_amaranth_core.toplevel:simulate"}
generate = {shell = "python -m my_amaranth_core"}
